const Localizations = {
  'languages': [
    'ar', // Araib
    'da', // Danish
    'de', // German
    'es', // Spanish
    'fr', // French
    'it', // Italian
    'ja', // Japanese
    'ko', // Korean
    'nl', // Dutch,
    'pl', // Polish
    'pt', // Portuguese
    'ro', // Romanian
    'ru', // Russian
    'zh_CN', // Simplified Chinese
    'zh_TW' // Traditional Chinese
  ],
  'header-why-myriad-button': {
    'ar': "؟Myriad لماذا ا",
    'da': "Hvorfor Myriaf?",
    'de': "Warum Myriad?",
    'es': "¿Por Qué Myriad?",
    'fr': "Pourquoi Myriad?",
    'it': "Perché Myriad?",
    'ja': "なぜMyriad？",
    'ko': "왜 Myriad?",
    'nl': "Waarom Myriad?",
    'pl': "Dlaczego Myriad?",
    'pt': "Por Que Myriad?",
    'ro': "De Ce Myriad?",
    'ru': "почему Myriad?",
    'zh_CN': "为什么 Myriad?",
    'zh_TW': "為什麼 Myriad?"
  },
  'header-wallets-button': {
    'ar': "محافظ",
    'da': "Tegnebøger",
    'de': "Geldbörsen",
    'es': "Billeteras",
    'fr': "Portefeuilles",
    'it': "Portafogli",
    'ja': "財布",
    'ko': "지갑",
    'nl': "Portefeuilles",
    'pl': "Portfele",
    'pt': "Carteiras",
    'ro': "Portofele",
    'ru': "бумажники",
    'zh_CN': "钱包",
    'zh_TW': "錢包"
  },
  'header-buy-button': {
    'ar': "يشترى",
    'da': "Købe",
    'de': "Kaufen",
    'es': "Comprar",
    'fr': "Acheter",
    'it': "Acquistare",
    'ja': "購入",
    'ko': "사다",
    'nl': "Kopen",
    'pl': "Kupować",
    'pt': "Comprar",
    'ro': "A cumpara",
    'ru': "купить",
    'zh_CN': "购买",
    'zh_TW': "購買"
  },
  'header-mine-button': {
    'ar': "تعدين",
    'da': "Minedrift",
    'de': "Bergbau",
    'es': "Minería",
    'fr': "Exploitation minière",
    'it': "Estrazione",
    'ja': "鉱業",
    'ko': "채광",
    'nl': "Mijnbouw",
    'pl': "Górnictwo",
    'pt': "Mineração",
    'ro': "Minerit",
    'ru': "Добыча",
    'zh_CN': "矿业",
    'zh_TW': "礦業"
  },
  'header-resources-button': {
    'ar': "مصادر",
    'da': "Ressourcer",
    'de': "Ressourcen",
    'es': "Recursos",
    'fr': "Ressources",
    'it': "Risorse",
    'ja': "リソース",
    'ko': "자원",
    'nl': "Middelen",
    'pl': "Zasoby",
    'pt': "Recursos",
    'ro': "Resurse",
    'ru': "Ресурсы",
    'zh_CN': "资源",
    'zh_TW': "資源"
  },
  'header-language-button': {
    'ar': "العربية",
    'da': "Dansk",
    'de': "Deutsch",
    'es': "Español",
    'fr': "Français",
    'it': "Italiano",
    'ja': "日本語",
    'ko': "한국의",
    'nl': "Nederlands",
    'pl': "Polski",
    'pt': "Português",
    'ro': "Română",
    'ru': "Русский",
    'zh_CN': "简体中文",
    'zh_TW': "繁體中文"
  },
  'hero-title': {
    'ar': "عملة للجميع.",
    'da': "En mønt til alle.",
    'de': "Eine Münze für alle.",
    'es': "Una moneda para todos.",
    'fr': "Une pièce de monnaie pour tout le monde.",
    'it': "Una moneta per tutti.",
    'ja': "みんなのためのコイン。",
    'ko': "모두를위한 동전.",
    'nl': "Een munt voor iedereen.",
    'pl': "Moneta dla wszystkich.",
    'pt': "Uma moeda para todos.",
    'ro': "O monedă pentru toată lumea.",
    'ru': "Монета для всех.",
    'zh_CN': "一个硬币给大家。",
    'zh_TW': "一個硬幣給大家。"
  },
  'hero-download-wallet-button': {
    'ar': "تحميل المحفظة",
    'da': "Download Tegnebog",
    'de': "Download Brieftasche",
    'es': "Descargar Billetera",
    'fr': "Télécharger le portefeuille",
    'it': "Scarica Il Portafoglio",
    'ja': "ウォレットをダウンロード",
    'ko': "지갑 다운로드",
    'nl': "Portemonnee Downloaden",
    'pl': "Pobierz Portfel",
    'pt': "Baixar Carteira",
    'ro': "Descărcați Portofel",
    'ru': "Скачать кошелек",
    'zh_CN': "下载钱包",
    'zh_TW': "下載錢包"
  },
  'hero-start-mining-button': {
    'ar': "بدء التعدين",
    'da': "Start Minedrift",
    'de': "Starten Sie das Mining",
    'es': "Comience a extraer",
    'fr': "Démarrer l&#39;exploitation",
    'it': "Inizia l&#39;estrazione",
    'ja': "マイニングを開始する",
    'ko': "마이닝 시작",
    'nl': "Begin Mijnbouw",
    'pl': "Rozpocznij Wydobycie",
    'pt': "Comece a Mineração",
    'ro': "Începeți mineritul",
    'ru': "Начать добычу",
    'zh_CN': "开始挖矿",
    'zh_TW': "開始挖礦"
  },
  'why-myriad-section-header': {
    'ar': "؟Myriad لماذا ا",
    'da': "Hvorfor Myriaf?",
    'de': "Warum Myriad?",
    'es': "¿Por Qué Myriad?",
    'fr': "Pourquoi Myriad?",
    'it': "Perché Myriad?",
    'ja': "なぜMyriad？",
    'ko': "왜 Myriad?",
    'nl': "Waarom Myriad?",
    'pl': "Dlaczego Myriad?",
    'pt': "Por Que Myriad?",
    'ro': "De Ce Myriad?",
    'ru': "почему Myriad?",
    'zh_CN': "为什么 Myriad?",
    'zh_TW': "為什麼 Myriad?"
  },
  'why-myriad-multi-algorithm-title': {
    'ar': "خوارزميات متعددة",
    'da': "Flere Algoritmer",
    'de': "Mehrere Algorithmen",
    'es': "Múltiples Algoritmos",
    'fr': "Plusieurs Algorithmes",
    'it': "Algoritmi Multipli",
    'ja': "複数のアルゴリズム",
    'ko': "다중 알고리즘",
    'nl': "Meerdere Algoritmen",
    'pl': "Wiele Algorytmów",
    'pt': "Múltiplos Algoritmos",
    'ro': "Multiple Algoritmi",
    'ru': "Несколько алгоритмов",
    'zh_CN': "多种算法",
    'zh_TW': "多種算法"
  },
  'why-myriad-multi-algorithm-text': {
    'ar': "لا تعد ولا تحصى هي العملة الأولى لدعم 5 خوارزميات، والمطاعم ل أسيك، غبو والتعدين وحدة المعالجة المركزية. حاليا، تتكون هذه الخوارزميات من SHA256d، سكريبت، مير-غروستل، سكين و يسكريبت. خوارزمية متعددة لا تعد ولا تحصى نهج يوفر مقاومة استثنائية 51٪ لأن هناك حاجة إلى مجموعة من الأجهزة المختلفة للعثور على 51٪ من الكتل.",
    'da': "Myriad er den første valuta til støtte for 5 algoritmer, catering til ASIC, GPU og CPU minedrift. I øjeblikket består disse algoritmer af SHA256d, Scrypt, Myr-Groestl, Skein og Yescrypt. Myriads multi-algoritme tilgang giver enestående 51% modstand, fordi en række forskellige hardware er nødvendige for at finde 51% af blokkene.",
    'de': "Myriad ist die erste Währung, die 5 Algorithmen unterstützt, die ASIC, GPU und CPU-Mining unterstützen. Derzeit bestehen diese Algorithmen aus SHA256d, Scrypt, Myr-Groestl, Skein und Yescrypt. Der Multialgorithmus von Myriad bietet eine außergewöhnliche Widerstandsfähigkeit von 51%, da eine Reihe unterschiedlicher Hardware benötigt wird, um 51% der Blöcke zu finden.",
    'es': "Myriad es la primera moneda en admitir 5 algoritmos, que atienden a ASIC, GPU y minería de CPU. Actualmente, esos algoritmos consisten en SHA256d, Scrypt, Myr-Groestl, Skein y Yescrypt. El enfoque de algoritmos múltiples de Myriad ofrece una resistencia excepcional del 51% porque se necesita una gama de hardware diferente para encontrar el 51% de los bloques.",
    'fr': "Myriad est la première devise à prendre en charge 5 algorithmes pour l&#39;extraction ASIC, GPU et CPU. Actuellement, ces algorithmes se composent de SHA256d, Scrypt, Myr-Groestl, Skein et Yescrypt. L&#39;approche multi-algorithme de Myriad offre une résistance exceptionnelle de 51% car une gamme de matériel différent est nécessaire pour trouver 51% des blocs.",
    'it': "Myriad is the first currency to support 5 algorithms, catering for ASIC, GPU and CPU mining. Currently, those algorithms consist of SHA256d, Scrypt, Myr-Groestl, Skein and Yescrypt. Myriad&#39;s multi algorithm approach offers exceptional 51% resistance because a range of different hardware is needed to find 51% of the blocks.",
    'ja': "Myriadは、ASIC、GPU、CPUマイニングの5つのアルゴリズムをサポートする最初の通貨です。現在、これらのアルゴリズムは、SHA256d、Scrypt、Myr-Groestl、Skein、およびYescryptで構成されています。 Myriadのマルチアルゴリズムアプローチは、ブロックの51％を見つけるためにさまざまなハードウェアの範囲が必要となるため、51％の耐性を提供します。",
    'ko': "Myriad는 ASIC, GPU 및 CPU 마이닝을위한 5 가지 알고리즘을 지원하는 최초의 통화입니다. 현재 이러한 알고리즘은 SHA256d, Scrypt, Myr-Groestl, Skein 및 Yescrypt로 구성됩니다. Myriad의 멀티 알고리즘 접근법은 블록의 51 %를 찾기 위해 다양한 하드웨어 범위가 필요하기 때문에 탁월한 51 % 저항을 제공합니다.",
    'nl': "Myriad is the first currency to support 5 algorithms, catering for ASIC, GPU and CPU mining. Currently, those algorithms consist of SHA256d, Scrypt, Myr-Groestl, Skein and Yescrypt. Myriad&#39;s multi algorithm approach offers exceptional 51% resistance because a range of different hardware is needed to find 51% of the blocks.",
    'pl': "Myriad to pierwsza waluta obsługująca 5 algorytmów, obsługująca kopie ASIC, GPU i procesora. Obecnie algorytmy te składają się z SHA256d, Scrypt, Myr-Groestl, Skein i Yescrypt. Metoda wielorakiego algorytmu Myriad oferuje wyjątkową 51-procentową odporność, ponieważ do znalezienia 51% bloków potrzebny jest szereg różnych urządzeń.",
    'pt': "Myriad é a primeira moeda a suportar 5 algoritmos, catering para ASIC, GPU e mineração de CPU. Atualmente, esses algoritmos consistem em SHA256d, Scrypt, Myr-Groestl, Skein e Yescrypt. A abordagem de múltiplos algoritmos da Myriad oferece uma excepcional resistência de 51%, porque uma gama de hardware diferente é necessária para encontrar 51% dos blocos.",
    'ro': "Myriad is the first currency to support 5 algorithms, catering for ASIC, GPU and CPU mining. Currently, those algorithms consist of SHA256d, Scrypt, Myr-Groestl, Skein and Yescrypt. Myriad&#39;s multi algorithm approach offers exceptional 51% resistance because a range of different hardware is needed to find 51% of the blocks.",
    'ru': "Myriad - первая валюта, поддерживающая 5 алгоритмов, обслуживающих ASIC, GPU и CPU. В настоящее время эти алгоритмы состоят из SHA256d, Scrypt, Myr-Groestl, Skein и Yescrypt. Множественный алгоритм Myriad предлагает исключительное сопротивление 51%, потому что для поиска 51% блоков требуется ряд различных аппаратных средств.",
    'zh_CN': "Myriad是第一个支持5种算法的货币，适用于ASIC，GPU和CPU挖掘。目前，这些算法由SHA256d，Scrypt，Myr-Groestl，Skein和Yescrypt组成。 Myriad的多算法方法提供了51％的优异阻力，因为需要一系列不同的硬件来找到51％的方块。",
    'zh_TW': "Myriad是第一個支持5種算法的貨幣，適用於ASIC，GPU和CPU挖掘。目前，這些算法由SHA256d，Scrypt，Myr-Groestl，Skein和Yescrypt組成。 Myriad的多算法方法提供了51％的優異阻力，因為需要一系列不同的硬件來找到51％的方塊。"
  },
  'why-myriad-merge-mining-title': {
    'ar': "دمج التعدين",
    'da': "Flette Mining",
    'de': "Bergbau Zusammenführen",
    'es': "Combinar Minería",
    'fr': "Fusionner L&#39;exploitation Minière",
    'it': "Unisci Estrazione",
    'ja': "マージ鉱業",
    'ko': "합병 광업",
    'nl': "Voeg Mijnbouw Samen",
    'pl': "Scalaj Wydobywanie",
    'pt': "Merge Mineração",
    'ro': "Mergeți miniere",
    'ru': "Слияние",
    'zh_CN': "合并采矿",
    'zh_TW': "合併採礦"
  },
  'why-myriad-merge-mining-text': {
    'ar': "يسمح دمج التعدين على خوارزميات SHA256d و سكريبت. وقد مكن هذا لا تعد ولا تحصى للاستفادة من هشراتس ضخمة المستخدمة حاليا من قبل القطع النقدية باستخدام هذه الخوارزميات. دمج التعدين، أو أوكسبو، يسمح للعمل يجري القيام بعملة الأم (مثل بيتكوين أو ليتسوان) لاستخدامها للعثور على كتل صالحة على بلوكشين لا تعد ولا تحصى.",
    'da': "Flet minedrift er tilladt på SHA256d og Scrypt algoritmerne. Dette har gjort det muligt for Myriad at udnytte de enorme hashrates, der i øjeblikket anvendes af mønter, der bruger disse algoritmer. Merge Mining, eller AuxPow, gør det muligt at udføre arbejdet for en forældemynt (f.eks. Bitcoin eller Litecoin), der bruges til at finde gyldige blokke på Myriads blokke.",
    'de': "Merge mining is allowed on the SHA256d and Scrypt algorithms. This has enabled Myriad to take advantage of the huge hashrates currently in use by coins using these algorithms. Merge Mining, or AuxPow, allows the work being done for a parent coin (such as Bitcoin or Litecoin) to be used to find valid blocks on Myriad&#39;s blockchain.",
    'es': "Merge mining está permitido en los algoritmos SHA256d y Scrypt. Esto le ha permitido a Myriad tomar ventaja de los enormes hashrates actualmente en uso por monedas usando estos algoritmos. Merge Mining, o AuxPow, permite que el trabajo que se realiza para una moneda principal (como Bitcoin o Litecoin) se use para encontrar bloques válidos en la cadena de bloques de Myriad.",
    'fr': "Merge mining is allowed on the SHA256d and Scrypt algorithms. This has enabled Myriad to take advantage of the huge hashrates currently in use by coins using these algorithms. Merge Mining, or AuxPow, allows the work being done for a parent coin (such as Bitcoin or Litecoin) to be used to find valid blocks on Myriad&#39;s blockchain.",
    'it': "Unisci mining è consentito negli algoritmi SHA256d e Scrypt. Ciò ha permesso a Myriad di sfruttare gli enormi hashreni attualmente in uso con le monete usando questi algoritmi. Unisci estrazione o AuxPow consente di utilizzare il lavoro svolto per una moneta madre (come Bitcoin o Litecoin) per trovare blocchi validi sulla blockchain di Myriad.",
    'ja': "マージマイニングはSHA256dアルゴリズムとScryptアルゴリズムで許可されています。これによりMyriadは、これらのアルゴリズムを使用するコインによって現在使用されている巨大なハッシュレートを利用することができました。 Merge MiningまたはAuxPowを使用すると、親コイン（BitcoinやLitecoinなど）の作業をMyriadのブロックチェーン上の有効なブロックを見つけるために使用できます。",
    'ko': "병합 마이닝은 SHA256d 및 Scrypt 알고리즘에서 허용됩니다. 이로써 Myriad는이 알고리즘을 사용하는 동전에 의해 현재 사용중인 거대한 해시를 이용할 수있게되었습니다. 병합 광업 또는 AuxPow를 사용하면 부모 동전 (예 : Bitcoin 또는 Litecoin)에 대한 작업을 통해 Myriad의 블록 체인에서 유효한 블록을 찾을 수 있습니다.",
    'nl': "Merge mining is allowed on the SHA256d and Scrypt algorithms. This has enabled Myriad to take advantage of the huge hashrates currently in use by coins using these algorithms. Merge Mining, or AuxPow, allows the work being done for a parent coin (such as Bitcoin or Litecoin) to be used to find valid blocks on Myriad&#39;s blockchain.",
    'pl': "Scalanie scalania jest dozwolone w algorytmach SHA256d i Scrypt. Umożliwiło to Myriadowi skorzystanie z ogromnych wachlarzów używanych obecnie przez monety za pomocą tych algorytmów. Merge Mining, czyli AuxPow, pozwala na wykonanie pracy nad monetą rodzicielską (np. Bitcoin lub Litecoin) w celu znalezienia prawidłowych bloków na blockchainie Myriad.",
    'pt': "Merge mining is allowed on the SHA256d and Scrypt algorithms. This has enabled Myriad to take advantage of the huge hashrates currently in use by coins using these algorithms. Merge Mining, or AuxPow, allows the work being done for a parent coin (such as Bitcoin or Litecoin) to be used to find valid blocks on Myriad&#39;s blockchain.",
    'ro': "Merge mining is allowed on the SHA256d and Scrypt algorithms. This has enabled Myriad to take advantage of the huge hashrates currently in use by coins using these algorithms. Merge Mining, or AuxPow, allows the work being done for a parent coin (such as Bitcoin or Litecoin) to be used to find valid blocks on Myriad&#39;s blockchain.",
    'ru': "Слияние может быть разрешено на алгоритмах SHA256d и Scrypt. Это позволило Myriad воспользоваться огромными хехратами, которые в настоящее время используются монетами, используя эти алгоритмы. Merge Mining или AuxPow позволяет выполнять работу над родительской монетой (например, биткойн или Litecoin) для поиска действительных блоков в цепочке цепочек Myriad.",
    'zh_CN': "SHA256d和Scrypt算法允许合并挖掘。这使得Myriad能够利用这些算法使用当前硬币使用的巨大hashrate。 Merge Mining或AuxPow允许使用母币（如比特币或莱特币）完成的工作用于在Myriad区块链上查找有效的区块。",
    'zh_TW': "SHA256d和Scrypt算法允許合併挖掘。這使得Myriad能夠利用這些算法使用當前硬幣使用的巨大hashrate。 Merge Mining或AuxPow允許使用母幣（如比特幣或萊特幣）完成的工作用於在Myriad區塊鏈上查找有效的區塊。"
  },
  'why-myriad-distribution-title': {
    'ar': "توزيع",
    'da': "Fordeling",
    'de': "Verteilung",
    'es': "Distribución",
    'fr': "Distribution",
    'it': "Distribuzione",
    'ja': "分布",
    'ko': "분포",
    'nl': "Distributie",
    'pl': "Dystrybucja",
    'pt': "Distribuição",
    'ro': "Distribuire",
    'ru': "распределение",
    'zh_CN': "分配",
    'zh_TW': "分配"
  },
  'why-myriad-distribution-text': {
    'ar': "تم الافراج عن عدد لا يحصى من البرية في 23 فبراير 2014 في 18:30 بالتوقيت العالمي المنسق. وجاءت أول كتلة الملغومة بعد 4 دقائق، وبالتالي تثبت أنه لم يكن هناك الفرضية. وبلغت المكافأة الأولية 000 1 مير، مما أدى إلى تخفيض عدد كل كتلته إلى 680 967 قطعة (حوالي 48 أسبوعا). إجمالي العرض حوالي 2 مليار مير. زمن الفدرة المستهدفة هو 60 ثانية، أو 300 ثانية لكل خوارزمية.",
    'da': "Myriad was released to the wild on February 23, 2014 at 18:30 UTC. The first mined block came 4 minutes later, thus establishing that there was no premine. The initial reward was 1,000 MYR, halving every 967,680 blocks (approximately 48 weeks). Total supply is approximately 2 billion MYR. Target block time is 60 seconds, or 300 seconds per algorithm.",
    'de': "Myriad wurde am 23. Februar 2014 um 18:30 UTC freigelassen. Der erste abgebaute Block kam 4 Minuten später, wodurch festgestellt wurde, dass es keine Premine gab. Die anfängliche Belohnung betrug 1.000 MYR und halbierte alle 967.680 Blöcke (ungefähr 48 Wochen). Das Gesamtangebot beträgt ca. 2 Milliarden MYR. Die Zielblockzeit beträgt 60 Sekunden oder 300 Sekunden pro Algorithmus.",
    'es': "Myriad fue lanzado al aire libre el 23 de febrero de 2014 a las 18:30 UTC. El primer bloque minado llegó 4 minutos más tarde, estableciendo así que no había ningún prejuicio. La recompensa inicial fue 1,000 MYR, reduciendo a la mitad cada 967,680 bloques (aproximadamente 48 semanas). El suministro total es de aproximadamente 2 mil millones de MYR. El tiempo del bloque objetivo es de 60 segundos o 300 segundos por algoritmo.",
    'fr': "Myriad was released to the wild on February 23, 2014 at 18:30 UTC. The first mined block came 4 minutes later, thus establishing that there was no premine. The initial reward was 1,000 MYR, halving every 967,680 blocks (approximately 48 weeks). Total supply is approximately 2 billion MYR. Target block time is 60 seconds, or 300 seconds per algorithm.",
    'it': "Miriade è stata rilasciata in libertà il 23 febbraio 2014 alle 18:30 UTC. Il primo blocco estratto è venuto 4 minuti più tardi, stabilendo così che non c&#39;era un premino. La ricompensa iniziale era di 1.000 MYR, dimezzando ogni 967.680 blocchi (circa 48 settimane). L&#39;offerta totale è di circa 2 miliardi di MYR. Il tempo di blocco target è 60 secondi o 300 secondi per algoritmo.",
    'ja': "Myriadは、2014年2月23日18:30 UTCに野生に放出されました。最初の採掘されたブロックは4分後に来たので、予期せぬことはないことを確認した。 当初の報酬は1,000 MYRで、967,680ブロック（約48週間）ごとに半分になりました。総供給量は約20億MYRです。ターゲットブロック時間は、アルゴリズムごとに60秒または300秒です。",
    'ko': "Myriad는 2014 년 2 월 23 일 18시 30 분 UTC에 야생에 공개되었습니다. 첫 번째 채광 된 블록은 4 분 후에 나왔고, 따라서 어떤 premine도 없다는 것을 확인했다. 초기 보상액은 1,000 MYR이었으며, 967,680 블록 (약 48 주)마다 절반이 절약되었습니다. 총 공급량은 약 20 억 MYR입니다. 목표 블록 시간은 알고리즘 당 60 초 또는 300 초입니다.",
    'nl': "Myriad is op 23 februari 2014 om 18.30 uur UTC in het wild uitgebracht. Het eerste gedolven blok kwam 4 minuten later, waarmee werd vastgesteld dat er geen premine was. De initiële beloning was 1.000 MYR, en halveerde elke 967.680 blokken (ongeveer 48 weken). Het totale aanbod is ongeveer 2 miljard MYR. Targetbloktijd is 60 seconden of 300 seconden per algoritme.",
    'pl': "Myriad został wypuszczony na wolność 23 lutego 2014 o 18:30 UTC. Pierwszy miniony blok pojawił się 4 minuty później, w ten sposób ustalając, że nie było premine. Początkowa nagroda wyniosła 1000 MYR, zmniejszając o połowę każde 967,680 bloków (około 48 tygodni). Całkowita podaż to około 2 miliardy MYR. Docelowy czas bloku wynosi 60 sekund lub 300 sekund na algorytm.",
    'pt': "Myriad foi liberada para a vida selvagem em 23 de fevereiro de 2014 às 18:30 UTC. O primeiro bloco minado ocorreu 4 minutos depois, estabelecendo assim que não havia nenhuma premissa. A recompensa inicial foi de 1.000 MYR, reduzindo para metade de 967.680 blocos (aproximadamente 48 semanas). A oferta total é de aproximadamente 2 bilhões de MYR. O tempo de bloco de destino é de 60 segundos, ou 300 segundos por algoritmo.",
    'ro': "Myriad a fost eliberat în sălbăticie la 23 februarie 2014 la ora 18:30 UTC. Primul bloc minat a venit 4 minute mai târziu, stabilind astfel că nu a existat nicio premine. Recompensa inițială a fost de 1.000 MYR, înjumătățind fiecare 967.680 blocuri (aproximativ 48 de săptămâni). Oferta totală este de aproximativ 2 miliarde de ani. Timpul de blocare a obiectivului este de 60 secunde sau 300 de secunde pe algoritm.",
    'ru': "Мириад был выпущен в дикую природу 23 февраля 2014 года в 18:30 UTC. Первый заминированный блок пришел через 4 минуты, тем самым установив, что не было премье. Первоначальная награда составляла 1000 MYR, вдвое уменьшая каждые 967 680 блоков (приблизительно 48 недель). Общий объем предложения составляет около 2 млрд. MYR. Целевое время составляет 60 секунд или 300 секунд на каждый алгоритм.",
    'zh_CN': "Myriad于2014年2月23日18:30在全球发布。第一块雷块在4分钟后来到，从而确定没有任何预兆。 最初的奖励是1000马币，每96768块（约48周）减半。总供给约20亿马币。目标块时间是60秒，或每个算法300秒。",
    'zh_TW': "Myriad於2014年2月23日18:30在全球發布。第一塊雷塊在4分鐘後來到，從而確定沒有任何預兆。 最初的獎勵是1000馬幣，每96768塊（約48週）減半。總供給約20億馬幣。目標塊時間是60秒，或每個算法300秒。"
  },
  'wallets-section-header': {
    'ar': "محافظ",
    'da': "Tegnebøger",
    'de': "Geldbörsen",
    'es': "Billeteras",
    'fr': "Portefeuilles",
    'it': "Portafogli",
    'ja': "財布",
    'ko': "지갑",
    'nl': "Portefeuilles",
    'pl': "Portfele",
    'pt': "Carteiras",
    'ro': "Portofele",
    'ru': "бумажники",
    'zh_CN': "钱包",
    'zh_TW': "錢包"
  },
  'wallets-desktop-title': {
    'ar': "الحاسوب",
    'da': "Computer",
    'de': "Computer",
    'es': "Computadora",
    'fr': "Ordinateur",
    'it': "Computer",
    'ja': "コンピューター",
    'ko': "컴퓨터",
    'nl': "Computer",
    'pl': "Komputer",
    'pt': "Computador",
    'ro': "Calculator",
    'ru': "компьютер",
    'zh_CN': "电脑",
    'zh_TW': "電腦"
  },
  'wallets-mobile-title': {
    'ar': "هاتف",
    'da': "Telefon",
    'de': "Telefon",
    'es': "Teléfono",
    'fr': "Téléphone",
    'it': "Telefono",
    'ja': "電話",
    'ko': "전화",
    'nl': "Telefoon",
    'pl': "Telefon",
    'pt': "telefone",
    'ro': "Telefon",
    'ru': "Телефон",
    'zh_CN': "电话",
    'zh_TW': "電話"
  },
  'wallets-source-title': {
    'ar': "مصدر الرمز",
    'da': "Kildekode",
    'de': "Quellcode",
    'es': "Código Fuente",
    'fr': "Code Source",
    'it': "Codice Sorgente",
    'ja': "ソースコード",
    'ko': "소스 코드",
    'nl': "Broncode",
    'pl': "Kod źródłowy",
    'pt': "Código Fonte",
    'ro': "Cod Sursa",
    'ru': "исходный код",
    'zh_CN': "源代码",
    'zh_TW': "源代碼"
  },
  'wallets-other-title': {
    'ar': "آخر",
    'da': "Andet",
    'de': "Andere",
    'es': "Otro",
    'fr': "Autre",
    'it': "Altro",
    'ja': "その他",
    'ko': "다른",
    'nl': "anders",
    'pl': "Inny",
    'pt': "De outros",
    'ro': "Alte",
    'ru': "Другие",
    'zh_CN': "其他",
    'zh_TW': "其他"
  },
  'buy-section-header': {
    'ar': "يشترى",
    'da': "Købe",
    'de': "Kaufen",
    'es': "Comprar",
    'fr': "Acheter",
    'it': "Acquistare",
    'ja': "購入",
    'ko': "사다",
    'nl': "Kopen",
    'pl': "Kupować",
    'pt': "Comprar",
    'ro': "A cumpara",
    'ru': "купить",
    'zh_CN': "购买",
    'zh_TW': "購買"
  },
  'buy-exchanges-title': {
    'ar': "التبادل",
    'da': "Udveksling",
    'de': "Austausch",
    'es': "Intercambios",
    'fr': "Des échanges",
    'it': "Scambi",
    'ja': "交流",
    'ko': "교류",
    'nl': "Uitwisselingen",
    'pl': "Wymiany",
    'pt': "Intercâmbios",
    'ro': "Schimburi",
    'ru': "Обмены",
    'zh_CN': "交易所",
    'zh_TW': "交易所"
  },
  'buy-spend-title': {
    'ar': "تنفق لا تعد ولا تحصى",
    'da': "Tilbring Myriad",
    'de': "Gib Myriad aus",
    'es': "Gasta Myriad",
    'fr': "Dépenser Myriad",
    'it': "Spendi Miriade",
    'ja': "無制限に過ごす",
    'ko': "무수한 지출",
    'nl': "Besteed Myriad",
    'pl': "Wydawaj Myriad",
    'pt': "Gaste muito",
    'ro': "Petreceți nenumărate",
    'ru': "Проводить мириады",
    'zh_CN': "花无数",
    'zh_TW': "花無數"
  },
  'buy-spend-text': {
    'ar': "على عكس العديد من كريبتوكيرنسيز الأخرى، والتجار في جميع أنحاء العالم تقبل بالفعل لا تعد ولا تحصى!",
    'da': "I modsætning til mange andre kryptokurver accepterer grossister over hele verden allerede Myriad!",
    'de': "Im Gegensatz zu vielen anderen Kryptowährungen akzeptieren Händler auf der ganzen Welt bereits Myriad!",
    'es': "¡A diferencia de muchas otras criptomonedas, los comerciantes de todo el mundo ya están aceptando Myriad!",
    'fr': "Contrairement à beaucoup d&#39;autres crypto-monnaies, les marchands du monde entier acceptent déjà Myriad!",
    'it': "A differenza di molte altre criptovalute, i commercianti di tutto il mondo accettano già Myriad!",
    'ja': "他の多くの暗号化通貨とは異なり、世界中の商人はすでにMyriadを受け入れています！",
    'ko': "많은 다른 cryptocurrencies와는 다른, 전세계 상인은 이미 Myriad를 받아들이고있다!",
    'nl': "In tegenstelling tot veel andere cryptocurrencies, accepteren handelaren over de hele wereld Myriad al!",
    'pl': "W przeciwieństwie do wielu innych kryptowalut, handlowcy na całym świecie już akceptują Myriad!",
    'pt': "Ao contrário de muitas outras criptografia, comerciantes de todo o mundo já estão aceitando Myriad!",
    'ro': "Spre deosebire de multe alte criptocuritate, negustorii din întreaga lume acceptă deja Myriad!",
    'ru': "В отличие от многих других криптоконкурсов, торговцы по всему миру уже принимают Myriad!",
    'zh_CN': "与其他许多加密货币不同，世界各地的商家已经接受了Myriad！",
    'zh_TW': "與其他許多加密貨幣不同，世界各地的商家已經接受了Myriad！"
  },
  'buy-on-text': {
    "ar":"شراء على",
    "da":"Køb videre",
    "de":"Kaufen Sie weiter",
    "es":"Comprar en",
    "fr":"Acheter sur",
    "it":"Acquista su",
    "ja":"購入する",
    "ko":"구입",
    "nl":"Koop op",
    "pl":"Kupić na",
    "pt":"Comprar em",
    "ro":"Cumpără de pe",
    "ru":"Купить",
    "zh_CN":"买上",
    "zh_TW":"買上"
  },
  'buy-view-merchants-button': {
    'ar': "عرض التجار",
    'da': "Se Forhandlere",
    'de': "Händler anzeigen",
    'es': "Ver Comerciantes",
    'fr': "Voir Les Marchands",
    'it': "Visualizza I Commercianti",
    'ja': "販売者の表示",
    'ko': "판매자보기",
    'nl': "Bekijk Verkopers",
    'pl': "Wyświetl Kupców",
    'pt': "Ver Comerciantes",
    'ro': "Vedeți Comercianții",
    'ru': "Просмотр продавцов",
    'zh_CN': "查看商家",
    'zh_TW': "查看商家"
  },
  'mine-section-header': {
    'ar': "تعدين",
    'da': "Minedrift",
    'de': "Bergbau",
    'es': "Minería",
    'fr': "Exploitation minière",
    'it': "Estrazione",
    'ja': "鉱業",
    'ko': "채광",
    'nl': "Mijnbouw",
    'pl': "Górnictwo",
    'pt': "Mineração",
    'ro': "Minerit",
    'ru': "Добыча",
    'zh_CN': "矿业",
    'zh_TW': "礦業"
  },
  'mine-getting-started-title': {
    'ar': "ابدء",
    'da': "Kom i gang",
    'de': "Anfangen",
    'es': "Empezando",
    'fr': "Commencer",
    'it': "Iniziare",
    'ja': "入門",
    'ko': "시작하기",
    'nl': "Ermee beginnen",
    'pl': "Pierwsze kroki",
    'pt': "Começando",
    'ro': "Noțiuni de bază",
    'ru': "Начиная",
    'zh_CN': "入门",
    'zh_TW': "入門"
  },
  'mine-getting-started-text': {
    'ar': "لإزالة الألغام لا تعد ولا تحصى، سوف تحتاج إلى أولا تحميل محفظة. ثم، واحدة من برامج التعدين المدرجة والنار بعيدا! إذا كنت بحاجة إلى القليل من المساعدة، يمكنك مشاهدة هذا البرنامج التعليمي على يوتوب.",
    'da': "For at minde Myriad skal du først downloade en tegnebog. Så, en af de nævnte minedrift software og brand væk! Hvis du har brug for lidt hjælp, kan du se denne YouTube-øvelse.",
    'de': "Um Myriad zu minen, müssen Sie zuerst eine Brieftasche herunterladen. Dann, eine der gelisteten Mining-Software und feuern Sie weg! Wenn du ein wenig Hilfe brauchst, kannst du dir dieses YouTube-Tutorial ansehen.",
    'es': "Para extraer Myriad, primero deberás descargar una billetera. ¡Entonces, uno de los softwares de minería listados y dispara! Si necesita un poco de ayuda, puede ver este tutorial de YouTube.",
    'fr': "Pour exploiter Myriad, vous devez d&#39;abord télécharger un portefeuille. Ensuite, l&#39;un des logiciels miniers répertoriés et le feu loin! Si vous avez besoin d&#39;un peu d&#39;aide, vous pouvez regarder ce didacticiel YouTube.",
    'it': "Per estrarre Myriad, devi prima scaricare un portafoglio. Quindi, uno dei software di mining elencati e sparare! Se hai bisogno di un piccolo aiuto, puoi guardare questo tutorial di YouTube.",
    'ja': "Myriadを鉱山するには、まず財布をダウンロードする必要があります。その後、記載されている鉱山ソフトウェアの1つを消してください！ちょっとした助けが必要な場合は、このYouTubeチュートリアルをご覧ください。",
    'ko': "Myriad를 채굴하려면 먼저 지갑을 다운로드해야합니다. 그런 다음 나열된 광산 소프트웨어 중 하나와 불이 꺼집니다! 약간의 도움이 필요하면 YouTube 튜토리얼을 시청하십시오.",
    'nl': "Om Myriad te mineren, moet je eerst een portemonnee downloaden. Dan, een van de vermelde mijnwaresoftware en schiet weg! Als je een beetje hulp nodig hebt, kun je deze YouTube-tutorial bekijken.",
    'pl': "Aby wydobyć Myriad, musisz najpierw pobrać portfel. Następnie jeden z wymienionych programów górniczych i odpal! Jeśli potrzebujesz pomocy, możesz obejrzeć samouczek na YouTube.",
    'pt': "Para explorar Myriad, você precisa primeiro fazer o download de uma carteira. Então, um dos softwares de mineração listados e dispare! Se você precisar de uma pequena ajuda, você pode assistir este tutorial do YouTube.",
    'ro': "Pentru Myriad, trebuie să descărcați mai întâi un portofel. Apoi, unul dintre programele miniere listate și trageți departe! Dacă aveți nevoie de puțin ajutor, puteți viziona acest tutorial YouTube.",
    'ru': "Чтобы мой Myriad, вам нужно сначала загрузить кошелек. Затем один из перечисленных программных продуктов для горных работ и сгорит! Если вам нужна небольшая помощь, вы можете посмотреть этот учебник YouTube.",
    'zh_CN': "为了挖掘Myriad，你需要先下载一个钱包。然后，列出的挖掘软件之一，开火！如果你需要一点帮助，你可以看这个YouTube教程。",
    'zh_TW': "為了挖掘Myriad，你需要先下載一個錢包。然後，列出的挖掘軟件之一，開火！如果你需要一點幫助，你可以看這個YouTube教程。"
  },
  'mine-mining-software-title': {
    'ar': "برامج التعدين",
    'da': "Mining software",
    'de': "Mining-Software",
    'es': "Software de minería",
    'fr': "Logiciel d&#39;exploitation minière",
    'it': "Software di data mining",
    'ja': "鉱業ソフトウェア",'ko': "광업 소프트웨어",
    'nl': "Mijnbouwsoftware",
    'pl': "Oprogramowanie górnicze",
    'pt': "Software de mineração",
    'ro': "Servicii miniere",
    'ru': "Горное программное обеспечение",
    'zh_CN': "挖掘软件",
    'zh_TW': "挖掘軟件"
  },
  'mine-mining-software-text': {
    'ar': "لا تعد ولا تحصى يدعم حفنة من برامج التعدين المختلفة. يمكنك الاختيار من القائمة أدناه لما خوارزمية كنت ترغب في الألغام مع اعتمادا على كيفية جهاز التعدين الخاص بك أو الجهاز هو الإعداد.",
    'da': "Myriad supports a handful of different mining softwares. You can choose from the list below for what algorithm you want to mine with depending on how your mining rig or device is setup.",
    'de': "Myriad unterstützt eine Handvoll verschiedener Mining-Software. Sie können aus der folgenden Liste auswählen, welchen Algorithmus Sie verwenden möchten, abhängig davon, wie Ihr Mining-Rig oder Gerät eingerichtet ist.",
    'es': "Myriad es compatible con un puñado de diferentes softwares de minería. Puede elegir de la lista a continuación para qué algoritmo desea extraer dependiendo de cómo esté configurada su plataforma o dispositivo de minería.",
    'fr': "Myriad prend en charge une poignée de logiciels miniers différents. Vous pouvez choisir dans la liste ci-dessous pour quel algorithme vous voulez exploiter en fonction de la configuration de votre plate-forme de forage ou de votre appareil.",
    'it': "Myriad supporta una manciata di diversi software di data mining. Puoi scegliere dall&#39;elenco sottostante per quale algoritmo vuoi estrarre, a seconda di come sono configurati il ​​tuo impianto di perforazione o il tuo dispositivo.",
    'ja': "Myriadは、さまざまなマイニングソフトウェアをサポートしています。マイニングリグやデバイスの設定に応じて、どのアルゴリズムを使用するかを以下のリストから選択できます。",
    'ko': "Myriad는 소수의 다양한 광산 소프트웨어를 지원합니다. 광산 장비 또는 장치 설정 방법에 따라 원하는 알고리즘을 아래 목록에서 선택할 수 있습니다.",
    'nl': "Myriad supports a handful of different mining softwares. You can choose from the list below for what algorithm you want to mine with depending on how your mining rig or device is setup.",
    'pl': "Myriad obsługuje kilka różnych programów górniczych. Możesz wybrać z poniższej listy algorytm, który chcesz wydobywać, w zależności od konfiguracji urządzenia górniczego lub urządzenia.",
    'pt': "Myriad supports a handful of different mining softwares. You can choose from the list below for what algorithm you want to mine with depending on how your mining rig or device is setup.",
    'ro': "Myriad sprijină o mână de diferite software-uri miniere. Aveți posibilitatea să alegeți din lista de mai jos ce algoritm doriți să aveți în funcție de modul în care instalația dvs. minieră sau dispozitivul este setat.",
    'ru': "Myriad поддерживает несколько программ интеллектуального анализа данных. Вы можете выбрать из приведенного ниже списка того, какой алгоритм вы хотите использовать, в зависимости от того, как настроена ваша установка или устройство.",
    'zh_CN': "Myriad支持一些不同的挖掘软件。您可以从下面的列表中选择要挖掘的算法，具体取决于您的采矿设备或设备的设置。",
    'zh_TW': "Myriad支持一些不同的挖掘軟件。您可以從下面的列表中選擇要挖掘的算法，具體取決於您的採礦設備或設備的設置。"
  },
  'mine-mining-pools-title': {
    'ar': "حمامات التعدين",
    'da': "Mining pools",
    'de': "Mining-Pools",
    'es': "Piscinas mineras",
    'fr': "Piscines minières",
    'it': "Piscine minerarie",
    'ja': "鉱山プール",
    'ko': "광업 수영장",
    'nl': "Mijnbaden",
    'pl': "Pule wydobywcze",
    'pt': "Piscinas de mineração",
    'ro': "Piscine miniere",
    'ru': "Горные бассейны",
    'zh_CN': "采矿池",
    'zh_TW': "採礦池"
  },
  'mine-mining-pools-text': {
    'ar': "يمكنك الألغام لا تعد ولا تحصى من خلال عدد من حمامات السباحة. إذا كنت لا تعرف ما تجمع التعدين هو، يمكنك معرفة المزيد هنا. لقد أدرجت حمامات التي تدعم حاليا التعدين ودمج التعدين من لا تعد ولا تحصى أدناه.",
    'da': "Du kan min Myriad gennem en række puljer. Hvis du ikke ved, hvad en minedrift er, kan du lære mere her. Vi har opregnet de puljer, der i øjeblikket understøtter minedrift og sammenfletning af Myriad minedrift nedenfor.",
    'de': "Sie können Myriad durch eine Reihe von Pools abbauen. Wenn Sie nicht wissen, was ein Mining-Pool ist, können Sie hier mehr erfahren. Wir haben die Pools aufgelistet, die derzeit das Mining und Merge-Mining von Myriad unterstützen.",
    'es': "Puedes extraer Myriad a través de varias piscinas. Si no sabe qué es un grupo de minería, puede obtener más información aquí. Hemos enumerado los grupos que actualmente son compatibles con la minería y la fusión de minería de Myriad a continuación.",
    'fr': "Vous pouvez exploiter Myriad à travers un certain nombre de pools. Si vous ne savez pas ce qu&#39;est un pool minier, vous pouvez en apprendre plus ici. Nous avons listé les pools qui supportent actuellement l&#39;exploitation minière et fusionner l&#39;exploitation minière de Myriad ci-dessous.",
    'it': "Puoi estrarre Myriad attraverso un numero di piscine. Se non sai cos&#39;è un pool minerario, puoi saperne di più qui. Abbiamo elencato i pool che attualmente supportano l&#39;estrazione e l&#39;unione di Myriad in basso.",
    'ja': "あなたは多くのプールを通じてMyriadを鉱山することができます。鉱山プールが何であるかわからない場合は、ここで詳細を知ることができます。以下のMyriadのマイニングとマージをサポートしているプールをリストアップしました。",
    'ko': "당신은 많은 수영장을 통해 무수한 사람을 살 수 있습니다. 광업 수영장이 무엇인지 모르는 경우 여기에서 자세히 알아볼 수 있습니다. 아래 Myriad의 마이닝 및 병합을 현재 지원하는 풀을 나열했습니다.",
    'nl': "Je kunt Myriad ontginnen via een aantal zwembaden. Als u niet weet wat een mijnbouwbad is, kunt u hier meer informatie vinden. We hebben de pools vermeld die momenteel mijnbouw ondersteunen en de mijnbouw van Myriad hieronder samenvoegen.",
    'pl': "Możesz wydobywać Myriad przez wiele basenów. Jeśli nie wiesz, co to jest basen górniczy, możesz dowiedzieć się więcej tutaj. Poniżej wymieniliśmy pule, które obecnie obsługują wydobywanie i scalanie Myriad.",
    'pt': "Você pode mina Myriad através de uma série de piscinas. Se você não sabe o que é um grupo de mineração, você pode aprender mais aqui. Nós listamos as piscinas que atualmente oferecem suporte a mineração e mescla a mineração da Myriad abaixo.",
    'ro': "Îmi poți aduce Myriad-ul prin mai multe bazine. Dacă nu știți ce este o piscină minieră, puteți afla mai multe aici. Am enumerat bazinele care susțin în prezent mineritul și o combină extracția minelor Myriad de mai jos.",
    'ru': "Вы можете разминировать Myriad через несколько бассейнов. Если вы не знаете, что такое горный пул, вы можете узнать больше здесь. Мы перечислили пулы, которые в настоящее время поддерживают добычу полезных ископаемых и слияние Minriad ниже.",
    'zh_CN': "你可以通过一些池来挖掘Myriad。如果你不知道矿池是什么，你可以在这里了解更多。我们在下面列出了当前支持挖掘和合并Myriad挖掘的池。",
    'zh_TW': "你可以通過一些池來挖掘Myriad。如果你不知道礦池是什麼，你可以在這裡了解更多。我們在下面列出了當前支持挖掘和合併Myriad挖掘的池。"
  },
  'mine-available-mining-software-title': {
    'ar': "برامج التعدين المتاحة",
    'da': "Tilgængelig Minedrift Software",
    'de': "Verfügbare Mining-Software",
    'es': "Software de Minería Disponible",
    'fr': "Logiciel d&#39;extraction Disponible",
    'it': "Software di Mining Disponibile",
    'ja': "利用可能なマイニングソフトウェア",
    'ko': "사용 가능한 마이닝 소프트웨어",
    'nl': "Beschikbare mijnsoftware",
    'pl': "Dostępne Oprogramowanie Górnicze",
    'pt': "Software de Mineração Disponível",
    'ro': "Software-ul Minier Disponibil",
    'ru': "Доступное программное обеспечение для добычи",
    'zh_CN': "可用的挖掘软件",
    'zh_TW': "可用的挖掘軟件"
  },
  'mine-sha256d-text': {
    'ar': "يمكنك استخدام أي SHA256d أسيك متوافق",
    'da': "Du må bruge enhver SHA256d kompatibel ASIC",
    'de': "Sie können einen SHA256d-kompatiblen ASIC verwenden",
    'es': "Puede usar cualquier ASIC compatible con SHA256d",
    'fr': "Vous pouvez utiliser n&#39;importe quel ASIC compatible SHA256d",
    'it': "È possibile utilizzare qualsiasi ASIC compatibile SHA256d",
    'ja': "任意のSHA256d互換ASICを使用できます",
    'ko': "SHA256d 호환 ASIC를 사용할 수 있습니다",
    'nl': "U kunt elke SHA256d compatibele ASIC gebruiken",
    'pl': "Możesz używać dowolnego ASIC zgodnego ze standardem SHA256d",
    'pt': "Você pode usar qualquer ASIC compatível com SHA256d",
    'ro': "Puteți utiliza orice ASIC compatibil SHA256d",
    'ru': "Вы можете использовать любую совместимую с SHA256d ASIC",
    'zh_CN': "您可以使用任何SHA256d兼容的ASIC",
    'zh_TW': "您可以使用任何SHA256d兼容的ASIC"
  },
  'mine-scrypt-text': {
    'ar': "يمكنك استخدام أي Scrypt أسيك متوافق",
    'da': "Du må bruge enhver Scrypt kompatibel ASIC",
    'de': "Sie können einen Scrypt-kompatiblen ASIC verwenden",
    'es': "Puede usar cualquier ASIC compatible con Scrypt",
    'fr': "Vous pouvez utiliser n&#39;importe quel ASIC compatible Scrypt",
    'it': "È possibile utilizzare qualsiasi ASIC compatibile Scrypt",
    'ja': "任意のScrypt互換ASICを使用できます",
    'ko': "Scrypt 호환 ASIC를 사용할 수 있습니다",
    'nl': "U kunt elke Scrypt compatibele ASIC gebruiken",
    'pl': "Możesz używać dowolnego ASIC zgodnego ze standardem Scrypt",
    'pt': "Você pode usar qualquer ASIC compatível com Scrypt",
    'ro': "Puteți utiliza orice ASIC compatibil Scrypt",
    'ru': "Вы можете использовать любую совместимую с Scrypt ASIC",
    'zh_CN': "您可以使用任何Scrypt兼容的ASIC",
    'zh_TW': "您可以使用任何Scrypt兼容的ASIC"
  },
  'mine-groestl-text': {
    'ar': "يمكنك استخدام أي Myr-Groestl أسيك متوافق",
    'da': "Du må bruge enhver Myr-Groestl kompatibel ASIC",
    'de': "Sie können einen Myr-Groestl-kompatiblen ASIC verwenden",
    'es': "Puede usar cualquier ASIC compatible con Myr-Groestl",
    'fr': "Vous pouvez utiliser n&#39;importe quel ASIC compatible Myr-Groestl",
    'it': "È possibile utilizzare qualsiasi ASIC compatibile Myr-Groestl",
    'ja': "任意のMyr-Groestl互換ASICを使用できます",
    'ko': "Myr-Groestl 호환 ASIC를 사용할 수 있습니다",
    'nl': "U kunt elke Myr-Groestl compatibele ASIC gebruiken",
    'pl': "Możesz używać dowolnego ASIC zgodnego ze standardem Myr-Groestl",
    'pt': "Você pode usar qualquer ASIC compatível com Myr-Groestl",
    'ro': "Puteți utiliza orice ASIC compatibil Myr-Groestl",
    'ru': "Вы можете использовать любую совместимую с Myr-Groestl ASIC",
    'zh_CN': "您可以使用任何Myr-Groestl兼容的ASIC",
    'zh_TW': "您可以使用任何Myr-Groestl兼容的ASIC"
  },
  'mine-skein-text': {
    'ar': "يمكنك استخدام أي Skein أسيك متوافق",
    'da': "Du må bruge enhver Skein kompatibel ASIC",
    'de': "Sie können einen Skein-kompatiblen ASIC verwenden",
    'es': "Puede usar cualquier ASIC compatible con Skein",
    'fr': "Vous pouvez utiliser n&#39;importe quel ASIC compatible Skein",
    'it': "È possibile utilizzare qualsiasi ASIC compatibile Skein",
    'ja': "任意のSkein互換ASICを使用できます",
    'ko': "Skein 호환 ASIC를 사용할 수 있습니다",
    'nl': "U kunt elke Skein compatibele ASIC gebruiken",
    'pl': "Możesz używać dowolnego ASIC zgodnego ze standardem Skein",
    'pt': "Você pode usar qualquer ASIC compatível com Skein",
    'ro': "Puteți utiliza orice ASIC compatibil Skein",
    'ru': "Вы можете использовать любую совместимую с Skein ASIC",
    'zh_CN': "您可以使用任何Skein兼容的ASIC",
    'zh_TW': "您可以使用任何Skein兼容的ASIC"
  },
  'mine-suggested-command-line-text': {
    'ar': "سطر الأوامر المقترح",
    'da': "Foreslået Kommandolinje",
    'de': "Vorgeschlagene Befehlszeile",
    'es': "Línea de Comando Sugerida",
    'fr': "Ligne de Commande Suggérée",
    'it': "Riga di Comando Suggerita",
    'ja': "推奨コマンドライン",
    'ko': "제안 된 명령 줄",
    'nl': "Voorgestelde Opdrachtregel",
    'pl': "Sugerowana Linia Poleceń",
    'pt': "Linha de Comando Sugerida",
    'ro': "Linie de Comandă Sugerată",
    'ru': "Рекомендуемая командная строка",
    'zh_CN': "建议的命令行",
    'zh_TW': "建議的命令行"
  },
  'mine-available-mining-pools-title': {
    'ar': "برك التعدين المتاحة",
    'da': "Tilgængelige Minedrift Puljer",
    'de': "Verfügbare Miningpools",
    'es': "Grupos de Minería Disponibles",
    'fr': "Pools Miniers Disponibles",
    'it': "Piscine Minerarie Disponibili",
    'ja': "利用可能な採掘プール",
    'ko': "사용 가능한 마이닝 풀",
    'nl': "Beschikbare Mijnzwembaden",
    'pl': "Dostępne Pule Wydobywcze",
    'pt': "Associações de Mineração Disponíveis",
    'ro': "Piscine Miniere Disponibile",
    'ru': "Доступные горные бассейны",
    'zh_CN': "可用的采矿池",
    'zh_TW': "可用的採礦池"
  },
  'mine-p2pool-nodes-text': {
    'ar': "P2Pool العقد",
    'da': "P2Pool noder",
    'de': "P2Pool Knoten",
    'es': "Nodos P2Pool",
    'fr': "Noeuds P2Pool",
    'it': "Nodi P2Pool",
    'ja': "P2Poolノード",
    'ko': "P2Pool 노드",
    'nl': "P2Pool-knooppunten",
    'pl': "Węzły P2Pool",
    'pt': "Nó P2Pool",
    'ro': "Nodurile P2Pool",
    'ru': "Узлы P2Pool",
    'zh_CN': "P2Pool节点",
    'zh_TW': "P2Pool節點"
  },
  'mine-pool-url-text': {
    'ar': "عنوان ورل للجمع",
    'da': "Pool-URL",
    'de': "Pool-URL",
    'es': "Pool URL",
    'fr': "Pool URL",
    'it': "URL del pool",
    'ja': "プールのURL",
    'ko': "풀 URL",
    'nl': "Pool-URL",
    'pl': "URL puli",
    'pt': "URL da associação",
    'ro': "URL-ul bazei de date",
    'ru': "URL пула",
    'zh_CN': "池网址",
    'zh_TW': "池網址"
  },
  'mine-to-be-decided-text': {
    'ar': "لكي تقرر",
    'da': "At blive besluttet",
    'de': "Ausgewählt sein",
    'es': "Por decidir",
    'fr': "Être décidé",
    'it': "Da decidere",
    'ja': "決定する",
    'ko': "결정되기",
    'nl': "Om beslist te worden",
    'pl': "Do ustalenia",
    'pt': "A ser decidido",
    'ro': "A fi decis",
    'ru': "Быть решенным",
    'zh_CN': "即将被决定",
    'zh_TW': "即將被決定"
  },
  'mine-run-your-own-node-text': {
    'ar': "تشغيل عقدة الخاصة بك",
    'da': "Kør din egen knudepunkt",
    'de': "Führen Sie Ihren eigenen Knoten aus",
    'es': "Ejecuta tu propio nodo",
    'fr': "Exécutez votre propre noeud",
    'it': "Esegui il tuo nodo",
    'ja': "自分のノードを実行する",
    'ko': "나만의 노드 실행",
    'nl': "Voer uw eigen knooppunt uit",
    'pl': "Uruchom swój własny węzeł",
    'pt': "Execute seu próprio nó",
    'ro': "Rulați propriul nod",
    'ru': "Запустить свой собственный узел",
    'zh_CN': "运行你自己的节点","zh_TW":
    "運行你自己的節點"
  },
  'mine-view-p2pool-instructions-button': {
    'ar': "عرض تعليمات P2Pool",
    'da': "Se P2Pool instruktioner",
    'de': "Zeigen Sie P2Pool-Anweisungen an",
    'es': "Ver las instrucciones de P2Pool",
    'fr': "Voir les instructions P2Pool",
    'it': "Visualizza le istruzioni di P2Pool",
    'ja': "P2Poolの指示を表示する",
    'ko': "P2Pool 지침보기",
    'nl': "Bekijk P2Pool-instructies",
    'pl': "Zobacz instrukcje P2Pool",
    'pt': "Ver instruções P2Pool",
    'ro': "Vizualizați instrucțiunile P2Pool",
    'ru': "Просмотреть инструкции P2Pool",
    'zh_CN': "查看P2Pool指令",
    'zh_TW': "查看P2Pool指令"
  },
  'mine-other-pools-text': {
    'ar': "حمامات أخرى",
    'da': "Andre Pools",
    'de': "Andere Pools",
    'es': "Otras piscinas",
    'fr': "Autres piscines",
    'it': "Altre piscine",
    'ja': "その他のプール",
    'ko': "기타 풀",
    'nl': "Andere zwembaden",
    'pl': "Inne baseny",
    'pt': "Outras Piscinas",
    'ro': "Alte piscine",
    'ru': "Другие пулы",
    'zh_CN': "其他游泳池",
    'zh_TW': "其他游泳池"
  },
  'mine-merge-mining-pools-text': {
    'ar': "دمج تجمع التعدين",
    'da': "Flette Mining Pools",
    'de': "Bergbau-Pools zusammenführen",
    'es': "Fusionar piscinas mineras",
    'fr': "Fusionner les pools miniers",
    'it': "Unisci pool di miniere",
    'ja': "鉱山プールの合併",
    'ko': "채광 풀 병합",
    'nl': "Samenvoegbekkens samenvoegen",
    'pl': "Połącz baseny wydobywcze",
    'pt': "Mesclar Piscinas Minerais",
    'ro': "Mergeți în bazinele miniere",
    'ru': "Объединить горные бассейны",
    'zh_CN': "合并挖掘池",
    'zh_TW': "合併挖掘池"
  },
  'mine-view-pool-details-button': {
    'ar': "عرض تفاصيل بركة",
    'da': "Se Pool Detaljer",
    'de': "Pooldetails anzeigen",
    'es': "Ver detalles de la piscina",
    'fr': "Afficher les détails de la piscine",
    'it': "Visualizza dettagli piscina",
    'ja': "プールの詳細を表示",
    'ko': "풀 세부 정보보기",
    'nl': "Bekijk poolgegevens",
    'pl': "Wyświetl szczegóły puli",
    'pt': "Ver detalhes da piscina",
    'ro': "Vizualizați detaliile băncii",
    'ru': "Просмотреть сведения о пуле",
    'zh_CN': "查看游泳池细节",
    'zh_TW': "查看游泳池細節"
  },
  'resources-section-header': {
    'ar': "مصادر",
    'da': "Ressourcer",
    'de': "Ressourcen",
    'es': "Recursos",
    'fr': "Ressources",
    'it': "Risorse",
    'ja': "リソース",
    'ko': "자원",
    'nl': "Middelen",
    'pl': "Zasoby",
    'pt': "Recursos",
    'ro': "Resurse",
    'ru': "Ресурсы",
    'zh_CN': "资源",
    'zh_TW': "資源"
  },
  'resources-information-title': {
    'ar': "معلومات",
    'da': "Information",
    'de': "Information",
    'es': "Información",
    'fr': "Information",
    'it': "Informazione",
    'ja': "情報",
    'ko': "정보",
    'nl': "Informatie",
    'pl': "Informacja",
    'pt': "Em formação",
    'ro': "informație",
    'ru': "Информация",
    'zh_CN': "信息",
    'zh_TW': "信息"
  },
  'resources-social-title': {
    'ar': "اجتماعي",
    'da': "Social",
    'de': "Sozial",
    'es': "Social",
    'fr': "Social",
    'it': "Sociale",
    'ja': "ソーシャル",
    'ko': "사회적인",
    'nl': "sociaal",
    'pl': "Społeczny",
    'pt': "Social",
    'ro': "Social",
    'ru': "Социальное",
    'zh_CN': "社会",
    'zh_TW': "社會"
  },
  'resources-other-title': {
    'ar': "آخر",
    'da': "Andet",
    'de': "Andere",
    'es': "Otro",
    'fr': "Autre",
    'it': "Altro",
    'ja': "その他",
    'ko': "다른",
    'nl': "anders",
    'pl': "Inny",
    'pt': "De outros",
    'ro': "Alte",
    'ru': "Другие",
    'zh_CN': "其他",
    'zh_TW': "其他"
  },
  'resources-cryptoid-explorer-button': {
    'ar': "المستكشف كريبتواد",
    'da': "Kryptoid explorer",
    'de': "Cryptoid Explorer",
    'es': "Explorador criptoideo",
    'fr': "Cryptoid explorer",
    'it': "Esploratore criptoide",
    'ja': "クリプトイドエクスプローラ",
    'ko': "크립토이드 탐색기",
    'nl': "Cryptoïde ontdekkingsreiziger",
    'pl': "Cryptoid explorer",
    'pt': "Explorador criptoideo",
    'ro': "Cryptoid explorer",
    'ru': "Cryptoid explorer",
    'zh_CN': "Cryptoid资源管理器",
    'zh_TW': "Cryptoid資源管理器"
  },
  'resources-insight-explorer-button': {
    'ar': "إنزيت إكسبلورر",
    'da': "Insight explorer",
    'de': "Insight Explorer",
    'es': "Explorador de Insight",
    'fr': "Insight explorer",
    'it': "Insight explorer",
    'ja': "Insight Explorer",
    'ko': "통찰력 탐색기",
    'nl': "Inzicht verkenner",
    'pl': "Eksplorator Insight",
    'pt': "Insight explorer",
    'ro': "Insight explorer",
    'ru': "Insight explorer",
    'zh_CN': "Insight Explorer",
    'zh_TW': "Insight Explorer"
  },
  'resources-abe-explorer-1-button': {
    'ar': "أبي إكسبلورر 1 (myralicious.com)",
    'da': "Abe Explorer 1 (myralicious.com)",
    'de': "Abe Explorer 1 (myralicious.com)",
    'es': "Abe Explorer 1 (myralicious.com)",
    'fr': "Abe Explorer 1 (myralicious.com)",
    'it': "Abe Explorer 1 (myralicious.com)",
    'ja': "Abe Explorer 1（myralicious.com）",
    'ko': "아베 익스플로러 1 (myralicious.com)",
    'nl': "Abe Explorer 1 (myralicious.com)",
    'pl': "Abe Explorer 1 (myralicious.com)",
    'pt': "Abe Explorer 1 (myralicious.com)",
    'ro': "Abe Explorer 1 (myralicious.com)",
    'ru': "Abe Explorer 1 (myralicious.com)",
    'zh_CN': "安倍资源管理器1（myralicious.com）",
    'zh_TW': "安倍資源管理器1（myralicious.com）"
  },
  'resources-abe-explorer-2-button': {
    'ar': "أبي إكسبلورر 2 (myralicious.com)",
    'da': "Abe Explorer 2 (myralicious.com)",
    'de': "Abe Explorer 2 (myralicious.com)",
    'es': "Abe Explorer 2 (myralicious.com)",
    'fr': "Abe Explorer 2 (myralicious.com)",
    'it': "Abe Explorer 2 (myralicious.com)",
    'ja': "Abe Explorer 2（myralicious.com）",
    'ko': "아베 익스플로러 2 (myralicious.com)",
    'nl': "Abe Explorer 2 (myralicious.com)",
    'pl': "Abe Explorer 2 (myralicious.com)",
    'pt': "Abe Explorer 2 (myralicious.com)",
    'ro': "Abe Explorer 2 (myralicious.com)",
    'ru': "Abe Explorer 2 (myralicious.com)",
    'zh_CN': "安倍资源管理器2（myralicious.com）",
    'zh_TW': "安倍資源管理器2（myralicious.com）"
  },
  'resources-network-status-button': {
    'ar': "حالة الشبكة",
    'da': "Netværksstatus",
    'de': "Netzwerkstatus",
    'es': "Estado de la Red",
    'fr': "L&#39;état du Réseau",
    'it': "Stato Della Rete",
    'ja': "ネットワークステータス",
    'ko': "네트워크 상태",
    'nl': "Netwerk Status",
    'pl': "Status Sieci",
    'pt': "Status da Rede",
    'ro': "Starea Rețelei",
    'ru': "Состояние сети",
    'zh_CN': "网络状态",
    'zh_TW': "網絡狀態"
  },
  'resources-reddit-button': {
    'ar': "رديت",
    'da': "Reddit",
    'de': "Reddit",
    'es': "Reddit",
    'fr': "Reddit",
    'it': "Reddit",
    'ja': "Reddit",
    'ko': "Reddit",
    'nl': "Reddit",
    'pl': "Reddit",
    'pt': "Reddit",
    'ro': "Reddit",
    'ru': "Reddit",
    'zh_CN': "书签交易",
    'zh_TW': "書籤交易"
  },
  'resources-bitcointalk-thread-button': {
    'ar': "بيتكوين نقاش الموضوع",
    'da': "BitcoinTalk Tråd",
    'de': "BitcoinTalk Thread",
    'es': "BitcoinTalk Thread",
    'fr': "BitcoinTalk Thread",
    'it': "BitcoinTalk Thread",
    'ja': "Bitcoin Talkスレッド",
    'ko': "Bitcoin 토크 스레드",
    'nl': "Bitcoin heeft discussie gevoerd",
    'pl': "BitcoinTalk Thread",
    'pt': "BitcoinTalk Thread",
    'ro': "BitcoinTalk Thread",
    'ru': "Биткойн Обсуждение темы",
    'zh_CN': "比特币谈话线程",
    'zh_TW': "比特幣談話線程"
  },
  'resources-twitter-button': {
    'ar': "تغريد",
    'da': "Twitter",
    'de': "Twitter",
    'es': "Gorjeo",
    'fr': "Twitter",
    'it': "cinguettio",
    'ja': "Twitter",
    'ko': "지저귀다",
    'nl': "tjilpen",
    'pl': "Świergot",
    'pt': "Twitter",
    'ro': "Stare de nervozitate",
    'ru': "щебет",
    'zh_CN': "推特",
    'zh_TW': "推特"
  },
  'resources-facebook-button': {
    'ar': "فيس بوك",
    'da': "Facebook",
    'de': "Facebook",
    'es': "Facebook",
    'fr': "Facebook",
    'it': "Facebook",
    'ja': "フェイスブック",
    'ko': "페이스 북",
    'nl': "Facebook",
    'pl': "Facebook",
    'pt': "Facebook",
    'ro': "Facebook",
    'ru': "facebook",
    'zh_CN': "Facebook的",
    'zh_TW': "Facebook的"
  },
  'resources-irc-channel-button': {
    'ar': "قناة الدردشة عبر الإنترنت",
    'da': "IRC Kanal",
    'de': "IRC Channel",
    'es': "Canal de Chat de Retransmisión de Internet",
    'fr': "IRC Channel",
    'it': "IRC channel",
    'ja': "インターネット中継チャットチャンネル",
    'ko': "인터넷 중계 채팅 채널",
    'nl': "Chat-Kanaal via Internet",
    'pl': "Kanał Czatu Internetowego",
    'pt': "IRC channel",
    'ro': "Canal de Conversație pe Internet",
    'ru': "Канал интернет-ретрансляции",
    'zh_CN': "互联网中继聊天频道",
    'zh_TW': "互聯網中繼聊天頻道"
  },
  'resources-game-faucet-button': {
    'ar': "لعبة الحنفية",
    'da': "Spilhaner",
    'de': "Spiel Wasserhahn",
    'es': "Game Faucet",
    'fr': "Robinet de Jeu",
    'it': "Gioco Faucet",
    'ja': "ゲームの蛇口",
    'ko': "게임 수도꼭지",
    'nl': "Spelkraan",
    'pl': "Kran w Grze",
    'pt': "Faucet do Jogo",
    'ro': "Robinet de Joc"
    ,'ru': "Игровой кран",
    'zh_CN': "游戏龙头",
    'zh_TW': "遊戲龍頭"
  },
  'resources-faucet-button': {
    'ar': "صنبور",
    'da': "Vandhane",
    'de': "Wasserhahn",
    'es': "Grifo",
    'fr': "Robinet",
    'it': "Rubinetto",
    'ja': "蛇口",
    'ko': "수도꼭지",
    'nl': "Kraan",
    'pl': "Kran",
    'pt': "Torneira",
    'ro': "Robinet",
    'ru': "кран",
    'zh_CN': "龙头",
    'zh_TW': "龍頭"
  },
  'resources-coinmarketcap-button': {
    'ar': "CoinMarketCap",
    'da': "CoinMarketCap",
    'de': "CoinMarketCap",
    'es': "CoinMarketCap",
    'fr': "CoinMarketCap",
    'it': "CoinMarketCap",
    'ja': "CoinMarketCap",
    'ko': "CoinMarketCap",
    'nl': "CoinMarketCap",
    'pl': "CoinMarketCap",
    'pt': "CoinMarketCap",
    'ro': "CoinMarketCap",
    'ru': "CoinMarketCap",
    'zh_CN': "CoinMarketCap",
    'zh_TW': "CoinMarketCap"
  },
  'resources-testnet-information-button': {
    'ar': "معلومات شبكة الاختبار",
    'da': "Test Netværksoplysninger",
    'de': "Testen Sie Netzwerkinformationen",
    'es': "Prueba de Información de Red",
    'fr': "Tester les Informations Réseau",
    'it': "Testare le Informazioni di Rete",
    'ja': "ネットワーク情報をテストする",
    'ko': "네트워크 정보 테스트",
    'nl': "Test Netwerkinformatie",
    'pl': "Sprawdź Informacje o Sieci",
    'pt': "Teste a informação da Rede",
    'ro': "Testați informațiile Despre Rețea",
    'ru': "Проверить сетевую информацию",
    'zh_CN': "测试网络信息",
    'zh_TW': "測試網絡信息"
  },
  'resources-cryptapus-myriad-page-button': {
    'ar': "Cryptap.us صفحة لا حصر لها",
    'da': "Cryptap.us Myriad Page",
    'de': "Cryptap.us Myriad Seite",
    'es': "Cryptap.us Myriad Page",
    'fr': "Cryptap.us Myriad Page",
    'it': "Cryptap.us Myriad Page",
    'ja': "Cryptap.us Myriad Page",
    'ko': "무수한 페이지 Cryptap.us",
    'nl': "Cryptap.us Myriad Page",
    'pl': "Cryptap.us Myriad Page",
    'pt': "Cryptap.us Myriad Page",
    'ro': "Cryptap.us Mii de pagini",
    'ru': "Cryptap.us Myriad Страница",
    'zh_CN': "Cryptap.us Myriad页面",
    'zh_TW': "Cryptap.us Myriad頁面"
  },
  'reddit-irc-myrbot-information-button': {
    'ar': "رديت / إيرك ميربوت المعلومات",
    'da': "Reddit / IRC myrbot information",
    'de': "Reddit / IRC Myrbot Informationen",
    'es': "Reddit / IRC myrbot información",
    'fr': "Informations sur Reddit / IRC myrbot",
    'it': "Informazioni su myrbot Reddit / IRC",
    'ja': "Reddit / IRC myrbot情報",
    'ko': "Reddit / IRC myrbot 정보",
    'nl': "Reddit / IRC myrbot-informatie",
    'pl': "Informacje o myrbot Reddit / IRC",
    'pt': "Informação do myrbot do Reddit / IRC",
    'ro': "Informații reddit / IRC myrbot",
    'ru': "Информация о Reddit / IRC myrbot",
    'zh_CN': "Reddit / IRC myrbot信息",
    'zh_TW': "Reddit / IRC myrbot信息"
  }
};
